//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("Resources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string account_number_text {
            get {
                return ResourceManager.GetString("account_number_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        internal static string btn_apply_filter {
            get {
                return ResourceManager.GetString("btn_apply_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btn_clear_filter {
            get {
                return ResourceManager.GetString("btn_clear_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter and sort all private and school dormitories / accommodations rooms.
        /// </summary>
        internal static string emu_intro_text {
            get {
                return ResourceManager.GetString("emu_intro_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privately-Owned Campus Dormitories.
        /// </summary>
        internal static string filter_dormitory_type_bot_dormitories {
            get {
                return ResourceManager.GetString("filter_dormitory_type_bot_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories.
        /// </summary>
        internal static string filter_dormitory_type_emu_dormitories {
            get {
                return ResourceManager.GetString("filter_dormitory_type_emu_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string filter_header_bed {
            get {
                return ResourceManager.GetString("filter_header_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter_header_filter_by {
            get {
                return ResourceManager.GetString("filter_header_filter_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchenette.
        /// </summary>
        internal static string filter_header_kitchenette {
            get {
                return ResourceManager.GetString("filter_header_kitchenette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessities.
        /// </summary>
        internal static string filter_header_nececities {
            get {
                return ResourceManager.GetString("filter_header_nececities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Options.
        /// </summary>
        internal static string filter_header_other_options {
            get {
                return ResourceManager.GetString("filter_header_other_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price .
        /// </summary>
        internal static string filter_header_price {
            get {
                return ResourceManager.GetString("filter_header_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Area.
        /// </summary>
        internal static string filter_header_room_area {
            get {
                return ResourceManager.GetString("filter_header_room_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC-Shower.
        /// </summary>
        internal static string filter_header_wc_shower {
            get {
                return ResourceManager.GetString("filter_header_wc_shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string filter_head_internet {
            get {
                return ResourceManager.GetString("filter_head_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string filter_head_tv {
            get {
                return ResourceManager.GetString("filter_head_tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000 to 2499.
        /// </summary>
        internal static string filter_options_price_responsive_2000_to_2499 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_2000_to_2499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2500 to 2999.
        /// </summary>
        internal static string filter_options_price_responsive_2500_to_2999 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_2500_to_2999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000 to 3499.
        /// </summary>
        internal static string filter_options_price_responsive_3000_to_3499 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_3000_to_3499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000 to 4999.
        /// </summary>
        internal static string filter_options_price_responsive_4000_to_4999 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_4000_to_4999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000 to 6000.
        /// </summary>
        internal static string filter_options_price_responsive_5000_to_6000 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_5000_to_6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 6000.
        /// </summary>
        internal static string filter_options_price_responsive_greater_than_6000 {
            get {
                return ResourceManager.GetString("filter_options_price_responsive_greater_than_6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 m2  to  20 m2.
        /// </summary>
        internal static string filter_options_room_area_responsive_10m2_to_20m2 {
            get {
                return ResourceManager.GetString("filter_options_room_area_responsive_10m2_to_20m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 m2  to  25 m2.
        /// </summary>
        internal static string filter_options_room_area_responsive_21m2_to_25m2 {
            get {
                return ResourceManager.GetString("filter_options_room_area_responsive_21m2_to_25m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 m2  to  30 m2.
        /// </summary>
        internal static string filter_options_room_area_responsive_26m2_to_30m2 {
            get {
                return ResourceManager.GetString("filter_options_room_area_responsive_26m2_to_30m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 30 m2.
        /// </summary>
        internal static string filter_options_room_area_responsive_greater_than_30m2 {
            get {
                return ResourceManager.GetString("filter_options_room_area_responsive_greater_than_30m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner (AC).
        /// </summary>
        internal static string filter_option_air_condition {
            get {
                return ResourceManager.GetString("filter_option_air_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunk.
        /// </summary>
        internal static string filter_option_bed_bunk {
            get {
                return ResourceManager.GetString("filter_option_bed_bunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string filter_option_bed_normal {
            get {
                return ResourceManager.GetString("filter_option_bed_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafeteria.
        /// </summary>
        internal static string filter_option_cafeteria {
            get {
                return ResourceManager.GetString("filter_option_cafeteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Heating/Cooling.
        /// </summary>
        internal static string filter_option_center_heating_cooling {
            get {
                return ResourceManager.GetString("filter_option_center_heating_cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string filter_option_generator {
            get {
                return ResourceManager.GetString("filter_option_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless.
        /// </summary>
        internal static string filter_option_internet_wireless {
            get {
                return ResourceManager.GetString("filter_option_internet_wireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        internal static string filter_option_internt_cable {
            get {
                return ResourceManager.GetString("filter_option_internt_cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats.
        /// </summary>
        internal static string filter_option_kitchenette_flats {
            get {
                return ResourceManager.GetString("filter_option_kitchenette_flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_kitchenette_room {
            get {
                return ResourceManager.GetString("filter_option_kitchenette_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string filter_option_laundry {
            get {
                return ResourceManager.GetString("filter_option_laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerator.
        /// </summary>
        internal static string filter_option_refrigerator {
            get {
                return ResourceManager.GetString("filter_option_refrigerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Tel..
        /// </summary>
        internal static string filter_option_room_tel {
            get {
                return ResourceManager.GetString("filter_option_room_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Hall.
        /// </summary>
        internal static string filter_option_tv_hall {
            get {
                return ResourceManager.GetString("filter_option_tv_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_tv_room {
            get {
                return ResourceManager.GetString("filter_option_tv_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string filter_option_wc_shower_common {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats.
        /// </summary>
        internal static string filter_option_wc_shower_flats {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_wc_shower_room {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 m2  to  20 m2.
        /// </summary>
        internal static string filter_range_10_to_20 {
            get {
                return ResourceManager.GetString("filter_range_10_to_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 m2  to  25 m2.
        /// </summary>
        internal static string filter_range_21_to_25 {
            get {
                return ResourceManager.GetString("filter_range_21_to_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 m2  to  30 m2.
        /// </summary>
        internal static string filter_range_26_to_30 {
            get {
                return ResourceManager.GetString("filter_range_26_to_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 30 m2.
        /// </summary>
        internal static string filter_range_greater_than_30 {
            get {
                return ResourceManager.GetString("filter_range_greater_than_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory Name.
        /// </summary>
        internal static string filter_select_dormitory_name {
            get {
                return ResourceManager.GetString("filter_select_dormitory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory Type.
        /// </summary>
        internal static string filter_select_dormitory_type {
            get {
                return ResourceManager.GetString("filter_select_dormitory_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string language_id {
            get {
                return ResourceManager.GetString("language_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string language_next {
            get {
                return ResourceManager.GetString("language_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dist/img/tr-flag.png.
        /// </summary>
        internal static string language_next_flag_url {
            get {
                return ResourceManager.GetString("language_next_flag_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string lang_code {
            get {
                return ResourceManager.GetString("lang_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Index/tr.
        /// </summary>
        internal static string lang_trans_link {
            get {
                return ResourceManager.GetString("lang_trans_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory name loading....
        /// </summary>
        internal static string loading_Dormitory_name {
            get {
                return ResourceManager.GetString("loading_Dormitory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading facility.....
        /// </summary>
        internal static string loading_facility {
            get {
                return ResourceManager.GetString("loading_facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender allocation loading….
        /// </summary>
        internal static string loading_gender_allocation {
            get {
                return ResourceManager.GetString("loading_gender_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room type loading….
        /// </summary>
        internal static string loading_room_type {
            get {
                return ResourceManager.GetString("loading_room_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmuLogo.png.
        /// </summary>
        internal static string logo_image_url {
            get {
                return ResourceManager.GetString("logo_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map view.
        /// </summary>
        internal static string map_view {
            get {
                return ResourceManager.GetString("map_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomodation.
        /// </summary>
        internal static string menu_accomodation {
            get {
                return ResourceManager.GetString("menu_accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitories &amp; Cafeteria Directorate.
        /// </summary>
        internal static string menu_dormitories_and_cafeteria {
            get {
                return ResourceManager.GetString("menu_dormitories_and_cafeteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results From the Map.
        /// </summary>
        internal static string results_from_map_text {
            get {
                return ResourceManager.GetString("results_from_map_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rooms found.
        /// </summary>
        internal static string rooms_found {
            get {
                return ResourceManager.GetString("rooms_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results:.
        /// </summary>
        internal static string search_result_text {
            get {
                return ResourceManager.GetString("search_result_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string sort_by {
            get {
                return ResourceManager.GetString("sort_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Area.
        /// </summary>
        internal static string sort_by_area {
            get {
                return ResourceManager.GetString("sort_by_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        internal static string sort_by_az {
            get {
                return ResourceManager.GetString("sort_by_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string sort_by_price {
            get {
                return ResourceManager.GetString("sort_by_price", resourceCulture);
            }
        }
    }
}
